### ISSUE TITLE
What if there is no primary key?

### ISSUE THREAD

**Issue by mraak** [richardschneider/yact#8]
Can it be used on tables with no primary key?

**Comment by richardschneider** [comment]
No it requires a primary key.

How would a change or delete be associated with a row if it didn't have a primary key?

**Comment by mraak** [comment]
Some tables just don't have PK's, and some might have multiple. Here's how I handled those:

- No PKs
Used the 'unique not null' column

- More PK's
Used first one that was found.

This was done manually now on some test tables and it worked. I will try on a real, larger DB and see how it works.

**Comment by richardschneider** [comment]
Okay we just have a definition problem.  To `yact` a primary key is just a column name that should be unique.  So your tests should work.

However, if the specified column is not unique, then there is no way to match the rows in the the audit table with actual rows in the table.

**Comment by mraak** [comment]
Ok, I was thinking about using a timestamp (if available), which *is* unique, but it would be possibly different in a real table, _deleted_ temp table and _inserted_ temp table. So this approach wouldn't work right?

I'm now working on an reflection code that builds the string needed for your script, so I'm factoring these findings in.

**Comment by richardschneider** [comment]
How about using an [identity column](https://msdn.microsoft.com/en-us/library/ms186775.aspx)

    CREATE TABLE dbo.YourTable (ID INT IDENTITY(1,1) NOT NULL, ... other columns);

**Comment by mraak** [comment]
Oh I'm not the one creating tables, I'm using an ancient bloated DB and trying to make sense out of it, that's why I need auditing. 

Unless I'd alter all the previous (700+) tables, add this field and populate it with unique values. BUT, the existing application code doesn't take this column into account - would it need to?

**Comment by richardschneider** [comment]
I suggest looking at DB schema.  I find it hard to believe that a DB with 700+ tables does not have use primary keys.

**Comment by mraak** [comment]
Of course there are PK's, just not for all the tables, and I'd like to audit all of them.
